OCS Alerts: Alerts for OCS plus files to reuse(helpers)
openshift/runbooks pull request #143
Opened 2023-10-20 12:17 UTC by jmolmo

Alerts:CephClusterErrorState, CephClusterWarningState, CephOSDVersionMismatch, PersistentVolumeUsageCritical

2023-10-23 08:12 UTC, jmolmo commented
/retest

2023-10-24 08:26 UTC, jmolmo commented
@iamniting , @nbalacha, Please provide review when you have time. Thanks in advance.

2023-10-25 04:30 UTC, iamniting commented
> @iamniting , @nbalacha, Please provide review when you have time. Thanks in advance.

@jmolmo I'm uncertain as to why I received the review request from the bot, as I don't possess the expertise necessary to evaluate this PR. I believe Umanga might be better suited for the task.

2023-10-25 09:55 UTC, jmolmo commented
@iamniting , @nbalacha , I do not know why the bot include you as reviewers.  

 @jan--f , @NautiluX, @ravitri , @RiRa12621 

Can you help me to review the PR?  It is needed a reviewer from OCS?

2023-10-26 17:54 UTC, RiRa12621 commented
Bot picks a random person from the list https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/OWNERS

2023-11-03 09:14 UTC, jmolmo commented
@RiRa12621 I need a review on this pull request. Who can help me?

2023-11-03 09:20 UTC, RiRa12621 commented
```
  - jarrpa
  - obnoxxx
  - umangachapagain
  - agarwal-mudit
  - nbalacha
  - BlaineEXE
  - nb-ohad
  - iamniting
  ```
  
  or probabaly @NautiluX can help you too

2023-11-03 09:48 UTC, jmolmo commented
@umangachapagain can you review the PR?

2023-11-06 11:36 UTC, umangachapagain requested changes

2023-11-06 11:36 UTC, umangachapagain commented on alerts/openshift-container-storage-operator/helpers/gatherLogs.md
> +    oc adm must-gather
```suggestion
    oc adm must-gather --image=<ODF-MUST-GATHER-IMAGE>
```

2023-11-24 04:33 UTC, agarwal-mudit approved these changes
/lgtm

2023-11-24 04:36 UTC, merged