add documentation for alerts related to ceph osd
openshift/runbooks pull request #150
Opened 2023-12-07 11:41 UTC by weirdwiz

this commit adds runbooks documentation for alerts related to ceph

2023-12-08 12:36 UTC, agarwal-mudit commented
/ok-to-test

2023-12-08 12:36 UTC, agarwal-mudit approved these changes
/lgtm

2023-12-09 07:22 UTC, agarwal-mudit commented
/hold

2023-12-11 08:51 UTC, jmolmo requested changes
review links to helpers files....

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephDataRecoveryTakingTooLong.md
> +   steps [here](helpers/sre-to-engineering-escalation.md#procedure).
Where is this helper file?

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephDataRecoveryTakingTooLong.md
> +- [Troubleshooting](helpers/troubleshootingCeph.md)
the file name is _troubleshootCeph.md_

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephOSDFlapping.md
> +[here](helpers/sre-to-engineering-escalation.md#procedure).
... file missing

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md
> +**Prerequisites:** [Prerequisites](helpers/prerequisites.md)
we do not have "prerequisites.md". I think not needed

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md
> +   [Check Ceph Network Connectivity SOP](check-ceph-network-connectivity.md).
we do not have this file.. maybe you need "helpers/networkConnectivity"

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md
> +   steps [here](sre-to-engineering-escalation.md#procedure).
we do not have this file

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md
> +- [Troubleshooting](helpers/troubleshooting.md)
probably you really want to have ... "helpers/troubleshootCeph.md"

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md
> +- [Gather Logs](helpers/gather_logs.md)
gatherLogs.md

2023-12-11 08:51 UTC, jmolmo commented on alerts/openshift-container-storage-operator/ODFPersistentVolumeMirrorStatus.md
> +[gather_logs](helpers/gather_logs.md) to provide more information to support
gatherLogs.md

2023-12-11 10:56 UTC, weirdwiz commented
updated the PR with the changes

2023-12-11 11:09 UTC, agarwal-mudit commented
/hold cancel

2023-12-11 12:33 UTC, jmolmo approved these changes
LGTM

2023-12-11 12:34 UTC, jmolmo commented
/lgtm

2023-12-11 12:55 UTC, weirdwiz commented
ptal @umangachapagain

2023-12-11 13:20 UTC, umangachapagain approved these changes

2023-12-11 13:22 UTC, umangachapagain commented
/lgtm

2023-12-11 13:32 UTC, merged