Modify MDS CPU runbook to scale mds pods.
openshift/runbooks pull request #189
Opened 2024-06-25 07:56 UTC by manishym

This was removed because the feature was not QA'd, now that it is, adding back the runback to horizontally scale MDS.

2024-06-25 11:04 UTC, parth-gr requested changes

2024-06-25 11:04 UTC, parth-gr commented on alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
> +blow command describes how to set the number of allocated CPU for MDS server.
below

2024-06-25 11:04 UTC, parth-gr commented on alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
> +Make sure we have enough CPU provisioned for MDS depending on the load.
add a note to increase the `activeCount` by 1 at a time

2024-06-25 11:04 UTC, parth-gr commented on alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
> +Make sure we have enough CPU provisioned for MDS depending on the load.
And also load share only happens if there are multiple pvc

2024-06-27 15:29 UTC, parth-gr approved these changes

2024-06-28 07:07 UTC, agarwal-mudit commented
/ok-to-test

2024-06-28 07:08 UTC, agarwal-mudit commented
cc @jmolmo

2024-07-02 06:49 UTC, agarwal-mudit approved these changes
/lgtm

2024-07-02 06:55 UTC, merged