Add runbook for StorageQuotaUtilizationThresholdReached
openshift/runbooks pull request #216
Opened 2024-10-17 15:47 UTC by rchikatw

- Add runbook for StorageQuotaUtilizationThresholdReached

2024-10-17 15:49 UTC, rchikatw commented
@leelavg can you review this.

2024-10-18 11:16 UTC, rchikatw commented
/ok-to-test

2024-10-21 06:22 UTC, leelavg commented
/ok-to-test

I don't think I have access too🤞🏼

2024-10-21 20:23 UTC, nb-ohad requested changes

2024-10-21 20:23 UTC, nb-ohad commented on alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
> +Persistent Volume Claim (PVC) usage is alarmingly very high, indicating an imminent risk of reaching full utilization of quota. Please see the alert documentation text for an exact threshold limit.
- PVC is a claim and does not have a usage, PVs have a usage
- you cannot use both "alarmingly" and "very" to describe usage, please choose one 
```suggestion
Persistent Volume (PV) usage is alarmingly high and might reach the allotted quota soon. Please see the alert documentation text for an exact threshold limit.
```

2024-10-21 20:23 UTC, nb-ohad commented on alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
> +This alert signifies that a Storage Quota is nearing its full capacity, potentially leading to blocking creation of new pvc on storage client side.
- Storage Qouta does not have a capacity, Qouta is just a value, not a thing that gets full.
```suggestion
This alert signifies that the storage utilization on the ODF client is close to reaching the configured storage quota, potentially leading to blocking the creation of new PVs on the client's cluster.
```

2024-10-21 20:23 UTC, nb-ohad commented on alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
> +The alert triggers when a Quota approaches or surpasses very high capacity limit for more details ref: the alert documentation text for an exact threshold limit.. It indicates the need to increase th
A quota is just a number/boundary. It does not and cannot "approaches" or "surpasses" anything.
```suggestion
The alert triggers when the storage utilization on a client's cluster is approaching or surpassing the configured storage quota limits.  This indicates the need to either increase the configured storage quota to accommodate more data or ask the client's cluster admin to delete unused PVs to free up space.
```

2024-11-11 07:03 UTC, agarwal-mudit commented
/ok-to-test

2024-11-11 07:45 UTC, nb-ohad commented on alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
> +Persistent Volume Claim (PVC) usage is alarmingly very high, indicating an imminent risk of reaching full utilization of quota. Please see the alert documentation text for an exact threshold limit.
ack

2024-11-11 07:45 UTC, nb-ohad commented on alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
> +This alert signifies that a Storage Quota is nearing its full capacity, potentially leading to blocking creation of new pvc on storage client side.
ack

2024-11-11 07:45 UTC, nb-ohad commented on alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
> +The alert triggers when a Quota approaches or surpasses very high capacity limit for more details ref: the alert documentation text for an exact threshold limit.. It indicates the need to increase th
ack

2024-11-11 07:47 UTC, rchikatw commented
/retest

2024-11-11 08:59 UTC, agarwal-mudit approved these changes
/lgtm

2024-11-11 09:03 UTC, merged