Add runbook for alert KubeAggregatedAPIErrors
openshift/runbooks pull request #30
Opened 2021-12-10 03:46 UTC by arajkumar

AggregatedAPIErrors alert was recently renamed[1] to KubeAggregatedAPIErrors.

This commit adds a runbook for the KubeAggregatedAPIErrors alert and keeps the old runbook as is to have backward compatibility.

[1] https://github.com/openshift/cluster-monitoring-operator/commit/1b85b557c8cbd4e944a5a70fbfd9f53d84218f5b

Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

2021-12-11 09:23 UTC, RiRa12621 commented
/lgtm

2021-12-13 09:48 UTC, simonpasquier commented
/lgtm

2021-12-16 08:42 UTC, arajkumar commented
/cc @jan--f

2021-12-16 10:55 UTC, simonpasquier commented
@arajkumar can you move it to the alerts/cluster-monitoring-operator directory since the alert is shipped by CMO?

2021-12-21 13:06 UTC, jan--f requested changes

2021-12-21 13:06 UTC, jan--f commented on alerts/KubeAggregatedAPIErrors.md
> +case, they are expired check [here][cert] how to add a new one.
```suggestion
The certificates are used by the aggregated APIs to validate requests. If a certificate is expired, check [the documentation][cert] how to renew it.
```

2021-12-21 13:06 UTC, jan--f commented on alerts/KubeAggregatedAPIErrors.md
> +check the end dates:
Should we add storing the cert in a file to the `oc get` command above?

2022-01-21 06:51 UTC, juzhao commented on alerts/KubeAggregatedAPIErrors.md
> +$ oc get apiservice
it is better to remove `$`, otherwise it will copied to clipboard, and we need to remove it manually to run the command, same for others

2022-01-21 07:09 UTC, juzhao commented on alerts/KubeAggregatedAPIErrors.md
> +API on the `openshift-apiserver` namespace, the prometheus-adapter on the
on the -> in the

2022-01-21 07:11 UTC, juzhao commented on alerts/KubeAggregatedAPIErrors.md
> +`openshift-operator-lifecycle-manager` namespace, and the API on the
on the -> in the

2022-04-22 08:40 UTC, simonpasquier commented
/lgtm

2022-04-22 08:50 UTC, merged